package homework.tables;

import homework.animals.Animal;
import homework.animals.Color;
import homework.db.IDBConnectionManager;
import homework.factory.AnimalFactory;
import homework.factory.AnimalType;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

public class AnimalTable extends AbsBaseTable implements InterfaceAnimalTable{

    private final AnimalFactory factory;

    public AnimalTable(AnimalFactory factory, IDBConnectionManager idbConnectionManager) throws SQLException {
        super("animals", idbConnectionManager);
        this.factory = factory;
        columns.put("id", "bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY");
        columns.put("name", "varchar(128)");
        columns.put("age", "bigint");
        columns.put("weight", "bigint");
        columns.put("color", "varchar(32)");
        columns.put("type","varchar(16)");
        create();
    }

    @Override
    public List<Animal> findAllAnimals() {
        String sqlQuery = "SELECT name, age, weight, color, type FROM " + tableName;

        return getAnimalsByQuery(sqlQuery);
    }

    @Override
    public List<Animal> find(Integer age, Integer weight, AnimalType type, String name) {
        StringBuilder sql = new StringBuilder("SELECT name, age, weight, color, type FROM ")
                .append(tableName)
                .append(" WHERE 1=1");
        if (age != null) {
            sql.append(" AND age = ").append(age);
        }
        if (weight != null) {
            sql.append(" AND weight = ").append(weight);
        }
        if (type != null) {
            sql.append(" AND type = '").append(type.name()).append("'");
        }
        if (name != null) {
            sql.append(" AND name = '").append(name.replace("'", "''")).append("'");
        }

        return getAnimalsByQuery(sql.toString());
    }


    private ArrayList<Animal> getAnimalsByQuery(String sqlQuery) {
        ArrayList<Animal> animals = new ArrayList<>();
        try(ResultSet rs = idbConnectionManager.executeWithData(sqlQuery)) {

            while (rs.next()) {
                String name = rs.getString("name");
                int age = rs.getInt("age");
                int weight = rs.getInt("weight");
                String color = rs.getString("color");
                String type = rs.getString("type");
                Animal animal = factory.create(AnimalType.fromString(type));
                animal.setName(name);
                animal.setAge(age);
                animal.setWeight(weight);
                animal.setColor(Color.fromString(color));
                animals.add(animal);
            }
        }catch (SQLException e){
            throw new RuntimeException(e);
        }
        return animals;
    }

    @Override
    public void create(Animal animal) {
        String sqlQuery = "INSERT INTO " + tableName + " (name, age, weight, color, type) VALUES (";
        sqlQuery += "'" + animal.getName().replace("'", "''") + "', " +
                animal.getAge() + ", " +
                animal.getWeight() + ", " +
                "'" + animal.getColor().name() + "', " +
                "'" + animal.getType().name() + "'";
        sqlQuery += ")";

        try {
            idbConnectionManager.executeUpdate(sqlQuery);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }


    @Override
    public void update(Animal animal) {
        String sqlQuery = "UPDATE " + tableName + " SET ";
        sqlQuery += "age = "+ animal.getAge() + ", ";
        sqlQuery+= "weight = " + animal.getWeight() + ", ";
        sqlQuery += "color = '" + animal.getColor().name() + "'";

        try {
            idbConnectionManager.executeUpdate(sqlQuery);
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

}

